"""Runtime env-trap generator.

Generates a small TypeScript or Python module that wraps env access
with a Proxy/dataclass that throws on undeclared keys with a clear,
dejavu-branded error message linking back to the project's
.env.example.

The generated stub is a runtime defense layer: any code that
accesses `env.LD_SDK_KEY` will throw at first execution if the var
isn't declared, so a fabrication that escaped the gen-time rewriter
still gets caught at dev/test time.

Output forms:

  TypeScript (default for Node / Next / Vite projects):
    A typed `env` object backed by Proxy, validates against a Zod
    schema generated from the indexed env vars. The literal-type
    union means tsc itself will refuse `env.UNDECLARED_KEY` if the
    consumer types their access through the typed accessor.

  Python:
    A frozen dataclass + a wrapping `os.environ` proxy that raises
    a custom `DejavuUndeclaredEnvError` with the dejavu link.

Both forms read env vars from `process.env` / `os.environ` at
runtime — they never store secret values; they only constrain
which keys are reachable.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

DEJAVU_LINK = ("https://github.com/HthSolid/claude-dejavu — "
                  "see `dejavu_lint_proposed_edit` and "
                  "`dejavu_propose_env_addition`")


def render_typescript(env_names: list[str], *,
                          file_name: str = "env.ts") -> str:
    """Generate a TypeScript module exposing `env` with a Proxy
    that throws on undeclared keys. Uses Zod for runtime parsing
    so missing/wrong-type values fail loudly during boot."""
    sorted_names = sorted(set(env_names))
    schema_lines = ",\n".join(
        f"  {name}: z.string().min(1).optional()"
        for name in sorted_names)
    union_type = " | ".join(f'"{n}"' for n in sorted_names) or '""'
    return f"""// AUTO-GENERATED by claude-dejavu — do not hand-edit
// To regenerate: claude-dejavu generate runtime-trap
// Source of truth: project .env.example + indexed env sources
// Last regenerated: dejavu manages this file's contents

import {{ z }} from "zod";

const declaredKeys = [
{",".join(chr(10) + '  "' + n + '"' for n in sorted_names)}
] as const;

export type DeclaredEnvKey = {union_type};

const envSchema = z.object({{
{schema_lines}
}});

const parsed = envSchema.safeParse(process.env);
if (!parsed.success) {{
  console.error("[claude-dejavu] env schema parse failed:", parsed.error.format());
  throw new Error(
    "[claude-dejavu] runtime env schema validation failed. " +
    "Fix .env.example or your local .env, then restart. " +
    "{DEJAVU_LINK}"
  );
}}

const declared = new Set<string>(declaredKeys);

/**
 * Typed env accessor. Throws on undeclared keys with a dejavu-
 * branded error so fabricated env names fail fast at dev/test time
 * instead of silently returning undefined.
 *
 *   env.DATABASE_URL      // OK if DATABASE_URL is declared
 *   env.MADE_UP_KEY       // throws DejavuUndeclaredEnvError
 *
 * To add a new declared key, run:
 *   claude-dejavu env propose <NAME> [--package=<sdk>] --apply
 * then re-run `claude-dejavu generate runtime-trap` to refresh
 * this file.
 */
export const env = new Proxy(parsed.data as Record<string, string | undefined>, {{
  get(target, prop: string) {{
    if (typeof prop !== "string") return undefined;
    if (!declared.has(prop)) {{
      throw new Error(
        `[claude-dejavu] env.${{prop}} is not declared in this project. ` +
        `Declared keys: ${{declaredKeys.join(", ")}}. ` +
        `If this is a real SDK convention, add it via ` +
        `\`claude-dejavu env propose ${{prop}} --apply\` ` +
        `then regenerate this file. ` +
        `({DEJAVU_LINK})`
      );
    }}
    return target[prop];
  }},
}});
"""


def render_python(env_names: list[str], *,
                     file_name: str = "dejavu_env.py") -> str:
    """Generate a Python module exposing `env` with a __getattr__
    trap that raises DejavuUndeclaredEnvError on undeclared keys."""
    sorted_names = sorted(set(env_names))
    declared_list = "\n".join(f'    "{n}",' for n in sorted_names)
    return f'''"""AUTO-GENERATED by claude-dejavu — do not hand-edit.
To regenerate: `claude-dejavu generate runtime-trap`
Source of truth: project .env.example + indexed env sources.
"""
from __future__ import annotations

import os


_DECLARED_ENV_KEYS = frozenset({{
{declared_list}
}})


class DejavuUndeclaredEnvError(KeyError):
    """Raised when code tries to read an env var that isn't declared
    in this project's .env.example or other indexed env sources.

    Message includes the dejavu link so the user knows how to
    declare a new key without bypassing the trap."""


class _EnvProxy:
    """Read-through wrapper over os.environ that refuses undeclared
    keys. Use either attribute access (env.DATABASE_URL) or
    bracket access (env["DATABASE_URL"]) — both go through the
    declared-set check."""

    def __getattr__(self, name: str) -> str | None:
        if name.startswith("_"):
            raise AttributeError(name)
        return self[name]

    def __getitem__(self, name: str) -> str | None:
        if name not in _DECLARED_ENV_KEYS:
            raise DejavuUndeclaredEnvError(
                f"env.{{name}} is not declared in this project. "
                f"Declared keys: {{sorted(_DECLARED_ENV_KEYS)}}. "
                f"To declare a new key: "
                f"`claude-dejavu env propose {{name}} --apply` "
                f"then `claude-dejavu generate runtime-trap`. "
                f"({DEJAVU_LINK})"
            )
        return os.environ.get(name)

    def __contains__(self, name: str) -> bool:
        return name in _DECLARED_ENV_KEYS


env = _EnvProxy()
'''


LANGUAGE_RENDERERS = {
    "typescript": render_typescript,
    "ts": render_typescript,
    "python": render_python,
    "py": render_python,
}


DEFAULT_OUTPUTS = {
    "typescript": "src/lib/env.ts",
    "python": "src/lib/dejavu_env.py",
}


def generate(env_names: list[str], *, language: str,
                output_path: Optional[Path] = None,
                project_root: Optional[Path] = None
                ) -> tuple[Path, str]:
    """Render the trap module and write it to disk. Returns
    (path, content).

    Raises ValueError on unknown language, OSError on write errors."""
    renderer = LANGUAGE_RENDERERS.get(language.lower())
    if not renderer:
        raise ValueError(
            f"unknown language `{language}`; supported: "
            f"{sorted(set(k for k in LANGUAGE_RENDERERS))}")
    if output_path is None:
        if project_root is None:
            project_root = Path.cwd()
        norm = ("typescript" if language.lower() in ("ts", "typescript")
                  else "python")
        output_path = project_root / DEFAULT_OUTPUTS[norm]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    content = renderer(env_names)
    output_path.write_text(content, encoding="utf-8")
    return output_path, content
