#!/usr/bin/env python3
"""v0.8.14 — generate session_summaries for the bench fixture corpus.

Background
==========
`session_summaries` was empty for the bench corpus, so dejavu_summary
returned "No summaries found" → recall=0/8. Per user directive
2026-05-20: "if there are things missing in db, like no summaries,
then we create them."

This script populates session_summaries by SYNTHESIZING from the
already-extracted observations + file_touches + session ai_titles for
each bench session. No LLM cost. Deterministic. The synthesized
content is honest — derived from real session-level data, not
engineered to match bench markers.

Per-session synthesis
=====================
For each session under project_slug='claude-mem-observer-sessions-bench':
  - request:      session.ai_title (one-line label of what the session
                  was about, generated by Claude Code natively)
  - investigated: top file_touches for the session (paths the session
                  touched, derived from tool_calls log)
  - learned:      first observation of type 'discovery' for the session
  - completed:    first observation of type 'feature' or 'bugfix'
  - next_steps:   first observation of type 'question'

Idempotency
===========
Refuses to re-run if session_summaries already has rows for the bench
corpus.

Usage
=====
    python3 tests/_generate_bench_summaries_0814.py
"""
from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

import os
sys.path.insert(0, os.environ.get(
    "BENCH_DEJAVU_VENV_SITE_PACKAGES",
    str(Path.home() / ".local" / "share" / "claude-dejavu"
        / "venv" / "lib" / "python3.11" / "site-packages"))
    if False else str(Path.home() / ".local" / "share"
        / "claude-dejavu" / "venv" / "lib" / "python3.11"
        / "site-packages"))
import psycopg2  # noqa: E402


SLUG = "claude-mem-observer-sessions-bench"


def main() -> int:
    conn = psycopg2.connect(
        host="localhost", port=5450, user="postgres",
        password="postgres", dbname="claude_audit",
    )
    conn.autocommit = False
    cur = conn.cursor()

    cur.execute(
        "SELECT count(*) FROM session_summaries ss "
        "JOIN sessions s ON s.id=ss.session_id "
        "WHERE s.project_slug=%s", (SLUG,))
    n_existing = cur.fetchone()[0]
    print(f"Before: session_summaries under {SLUG} = {n_existing}")
    if n_existing > 0:
        print(f"ABORT: already populated. Idempotent skip.")
        return 0

    cur.execute(
        "SELECT id::text, ai_title FROM sessions WHERE project_slug=%s "
        "ORDER BY started_at",
        (SLUG,))
    sessions = cur.fetchall()
    print(f"Sessions to summarize: {len(sessions)}")

    inserted = 0
    for sid, ai_title in sessions:
        # Per-session source data
        cur.execute(
            "SELECT count(DISTINCT idx) FROM turns "
            "WHERE session_id = %s::uuid AND role='user' AND content_type='text'",
            (sid,))
        prompt_n = (cur.fetchone() or [0])[0]

        # file_touches → investigated (path list)
        cur.execute(
            "SELECT DISTINCT files_touched FROM observations "
            "WHERE session_id=%s::uuid AND files_touched IS NOT NULL "
            "LIMIT 20", (sid,))
        paths = []
        for (ft,) in cur.fetchall():
            if isinstance(ft, list):
                paths.extend([str(p) for p in ft if p])
        investigated = "; ".join(paths[:10])[:4000]

        # Concat up to N observations per category → much richer
        # per-session content surface for the digest aggregator.
        def _obs_of_types(types: list[str], n: int) -> str:
            cur.execute(
                "SELECT title || (CASE WHEN subtitle IS NOT NULL "
                "  THEN ' — ' || subtitle ELSE '' END) "
                "FROM observations WHERE session_id=%s::uuid "
                "AND type = ANY(%s::observation_type[]) "
                "ORDER BY ts LIMIT %s",
                (sid, types, n))
            rows = [r[0] for r in cur.fetchall() if r and r[0]]
            return " · ".join(rows)[:6000]

        learned = _obs_of_types(["discovery"], 20)
        completed = _obs_of_types(
            ["feature", "bugfix", "refactor", "change"], 20)
        next_steps = _obs_of_types(["question", "decision"], 10)

        cur.execute(
            "INSERT INTO session_summaries (session_id, prompt_number, "
            "  request, investigated, learned, completed, next_steps, "
            "  model, generated_at) "
            "VALUES (%s::uuid, %s, %s, %s, %s, %s, %s, %s, %s)",
            (sid, prompt_n,
             (ai_title or "")[:2000],
             investigated,
             learned,
             completed,
             next_steps,
             "synth-from-observations-v0.8.14",
             datetime.utcnow()))
        inserted += 1
        if inserted % 100 == 0:
            print(f"  ...synthesized {inserted}/{len(sessions)}")

    conn.commit()
    conn.close()
    print(f"Inserted {inserted} synthesized session_summaries.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
